apiVersion: oda.tmforum.org/v1beta3
kind: Component
metadata:
  name: {{ .Release.Name }}-{{ .Values.component.name }}
  labels:
    oda.tmforum.org/componentName: {{ .Values.component.name }}
spec:
  type: {{ .Values.component.type }}
  version: {{ .Values.component.version }}
  description: "TMF673 Geographic Address Management API - ODA Component providing standardized interface to address management system"
  maintainers:
    - name: "ODA Component Developer"
      email: "developer@example.com"
  owners:
    - name: "Organization Name"
      email: "owner@example.com"

  coreFunction:
    exposedAPIs:
      - name: geographicaddressmanagement
        apiType: openapi
        specification:
          - "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
        implementation: {{ .Release.Name }}-geographicaddress
        path: /tmf-api/geographicAddressManagement/v4
        developerUI: /tmf-api/geographicAddressManagement/v4/docs
        port: {{ .Values.geographicaddress.service.port }}
    dependentAPIs: []

  eventNotification:
    publishedEvents:
      - name: GeographicAddressValidationCreateEvent
        hub: /tmf-api/geographicAddressManagement/v4/hub
      - name: GeographicAddressValidationStateChangeEvent
        hub: /tmf-api/geographicAddressManagement/v4/hub
      - name: GeographicAddressValidationDeleteEvent
        hub: /tmf-api/geographicAddressManagement/v4/hub
    subscribedEvents: []

  managementFunction:
    exposedAPIs: []

  securityFunction:
    controllerRole: {{ .Values.oda.canvas.role }}
    exposedAPIs: []
