apiVersion: oda.tmforum.org/v1beta3
kind: Component
metadata:
  name: {{ .Release.Name }}-{{ .Values.component.name }}
  labels:
    oda.tmforum.org/componentName: {{ .Values.component.name }}
spec:
  type: {{ .Values.component.type }}
  version: {{ .Values.component.version }}
  description: "TMF673 Geographic Address Management API - ODA Component providing standardized interface to address management system"
  maintainers:
    - name: "ODA Component Developer"
      email: "developer@example.com"
  owners:
    - name: "Organization Name"
      email: "owner@example.com"

  coreFunction:
    exposedAPIs:
      - name: geographicaddressmanagement
        id: TMF673
        version: 4
        specification: "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
        implementation: {{ .Release.Name }}-geographicaddress
        path: /tmf-api/geographicAddressManagement/v4
        developerUI: /tmf-api/geographicAddressManagement/v4/docs
        port: {{ .Values.geographicaddress.service.port }}
        resources:
          - geographicAddress:
              - GET /geographicAddress
              - GET /geographicAddress/{id}
          - geographicSubAddress:
              - GET /geographicSubAddress
          - geographicAddressValidation:
              - GET /geographicAddressValidation
              - GET /geographicAddressValidation/{id}
              - POST /geographicAddressValidation
              - PATCH /geographicAddressValidation/{id}
              - DELETE /geographicAddressValidation/{id}
    dependentAPIs: []

  eventNotification:
    publishedEvents:
      - name: GeographicAddressValidationCreateEvent
        specification: "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
        hub: /tmf-api/geographicAddressManagement/v4/hub
        implementation: {{ .Release.Name }}-geographicaddress
        port: {{ .Values.geographicaddress.service.port }}
      - name: GeographicAddressValidationStateChangeEvent
        specification: "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
        hub: /tmf-api/geographicAddressManagement/v4/hub
        implementation: {{ .Release.Name }}-geographicaddress
        port: {{ .Values.geographicaddress.service.port }}
      - name: GeographicAddressValidationDeleteEvent
        specification: "https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.0.swagger.json"
        hub: /tmf-api/geographicAddressManagement/v4/hub
        implementation: {{ .Release.Name }}-geographicaddress
        port: {{ .Values.geographicaddress.service.port }}
    subscribedEvents: []

  managementFunction:
    exposedAPIs:
      - name: metrics
        id: prometheus
        version: 1
        implementation: {{ .Release.Name }}-geographicaddress
        path: /metrics
        port: {{ .Values.geographicaddress.service.port }}

  securityFunction:
    controllerRole: {{ .Values.oda.canvas.role }}
    exposedAPIs: []
