{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: {{ .Release.Name }}-mongodb
    oda.tmforum.org/componentName: {{ .Values.component.name }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
  - port: {{ .Values.mongodb.service.port }}
    targetPort: {{ .Values.mongodb.service.port }}
    protocol: TCP
    name: mongodb
  selector:
    app: {{ .Release.Name }}-mongodb
{{- end }}
